CREATE TABLE IF NOT EXISTS industry_master (business_id VARCHAR(64) PRIMARY KEY, name VARCHAR(255), category_code VARCHAR(64), category_path TEXT, algorithm_type VARCHAR(16));
CREATE TABLE IF NOT EXISTS keyword_templates (id BIGINT AUTO_INCREMENT PRIMARY KEY, business_id VARCHAR(64), keyword VARCHAR(255), keyword_code VARCHAR(64), cnt INT DEFAULT 0, FOREIGN KEY (business_id) REFERENCES industry_master(business_id));
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2319608132', '프리미엄 온핏 개포점 헬스 PT', '', '스포츠시설', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2319608132', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2319608132', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2319608132', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_204273459', '파프짐 개포PT 2호점', '', '스포츠시설', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_204273459', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_204273459', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_204273459', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2096206249', '닥터포바디 퍼스널트레이닝', '', '스포츠시설', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2096206249', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2096206249', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2096206249', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2741719708', '바디퓨처 퍼스널트레이닝 PT 개포점', '', '헬스장', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2741719708', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2741719708', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2741719708', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3811054522', '훈짐PT', '', '헬스장', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3811054522', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3811054522', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3811054522', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2294291958', '테레스 필라테스 개포', '', '필라테스', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2294291958', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2294291958', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2294291958', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_350427014', '하우스오브필라테스', '', '필라테스', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_350427014', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_350427014', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_350427014', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_719412357', '헤아림 필라테스 앤 자이로토닉 강남', '', '필라테스', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_719412357', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_719412357', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_719412357', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2028192528', '필라테스진심 개포본점', '', '필라테스', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2028192528', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2028192528', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2028192528', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_4098451886', '쏘핏PT&필라테스', '', '스포츠시설', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4098451886', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4098451886', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4098451886', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3524260192', '시소요가 개포', '', '요가,명상', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3524260192', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3524260192', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3524260192', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3715482994', '애프터 요가 매봉역점', '', '요가원', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3715482994', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3715482994', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3715482994', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2825534975', 'M요가 필라테스 & PT 양재점', '', '요가원', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2825534975', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2825534975', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2825534975', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_673267811', '요가398', '', '요가원', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_673267811', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_673267811', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_673267811', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1466332281', '버핏그라운드 도곡', '', '헬스장', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1466332281', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1466332281', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1466332281', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_411714', '리애', '', '카페', 'TYPE_B');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_411714', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_411714', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_411714', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2508517013', '스타벅스 개포동점', '', '순대,순댓국', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2508517013', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2508517013', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2508517013', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1173758339', '다담순대국', '', '차', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1173758339', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1173758339', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1173758339', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3922941446', '타이티 플래그십스토어', '', '찌개,전골', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3922941446', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3922941446', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3922941446', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1527911034', '의정부원조부대찌개', '', '베이커리', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1527911034', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1527911034', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1527911034', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2508517013', '스타벅스 개포동점', '', '차', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2508517013', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2508517013', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2508517013', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3922941446', '타이티 플래그십스토어', '', '베이커리', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3922941446', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3922941446', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3922941446', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1303074725', '곤트란쉐리에 개포동점', '', '카페', 'TYPE_B');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1303074725', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1303074725', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1303074725', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_780657964', '쿠지 커피 로스터스 개포', '', '베이커리', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_780657964', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_780657964', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_780657964', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2219929129', '파리바게뜨 개포행복점', '', '차', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2219929129', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2219929129', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2219929129', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1723703351', '꼬치리 숯불구이', '', '맥주,호프', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1723703351', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1723703351', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1723703351', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3879880485', '비어씨티', '', '와인', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3879880485', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3879880485', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3879880485', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_146641314', '와인과 함께_개포본점', '', '포장마차', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_146641314', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_146641314', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_146641314', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3873405356', '춘화포차', '', '바(BAR)', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3873405356', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3873405356', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3873405356', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3233323339', '부르', '', '이자카야', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3233323339', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3233323339', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3233323339', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1230327886', '박준뷰티랩 개포점', '', 'perm', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1230327886', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1230327886', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1230327886', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3340988045', '김회쌀롱', '', 'perm', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3340988045', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3340988045', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3340988045', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_4288461272', '가온헤어룸', '', 'perm', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4288461272', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4288461272', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4288461272', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2707919019', '뉴맨헤어', '', 'cut', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2707919019', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2707919019', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2707919019', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1840782972', '헤어살롱봄', '', 'color', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1840782972', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1840782972', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1840782972', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('sample_cafe_01', '샘플 카페', 'CE7', '카페,디저트', 'TYPE_B');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('sample_cafe_01', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('sample_cafe_01', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('sample_cafe_01', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('sample_food_01', '샘플 맛집', 'FD6', '음식점,한식', 'TYPE_B');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('sample_food_01', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('sample_food_01', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('sample_food_01', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('sample_gym_01', '샘플 헬스장', 'G109', '헬스장', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('sample_gym_01', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('sample_gym_01', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('sample_gym_01', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3633525257', '영독학원', '', '영어교육', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3633525257', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3633525257', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3633525257', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_332225804', '리드101 개포구룡점', '', '영어교육', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_332225804', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_332225804', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_332225804', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_951768049', '피에스에이개포어학학원', '', '영어교육', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_951768049', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_951768049', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_951768049', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3320802662', '애플트리개포어학학원', '', '영어교육', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3320802662', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3320802662', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3320802662', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1670500427', '키즈엔리딩 강남개포점', '', '영어교육', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1670500427', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1670500427', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1670500427', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_530165994', '그린램프라이브러리 관리형독서실 대치캠퍼스', '', '독서실', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_530165994', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_530165994', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_530165994', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2583217221', '독학재수 학고재', '', '독서실', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2583217221', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2583217221', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2583217221', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1376328997', '메이커스 관리형 독서실', '', '독서실', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1376328997', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1376328997', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1376328997', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3517536803', '몰입스파르타 관리형독서실', '', '독서실', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3517536803', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3517536803', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3517536803', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2887049157', '비전21 N관 독서실', '', '독서실', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2887049157', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2887049157', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2887049157', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1270108505', '당일꽃배달,개업식화분,근조환,장례식꽃,생일꽃,오브제화환배송', '', '꽃집,꽃배달', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1270108505', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1270108505', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1270108505', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1528969529', '종로꽃집', '', '꽃집,꽃배달', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1528969529', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1528969529', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1528969529', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_4037115624', '당일전국꽃배달59000원,근조,화환,난,꽃바구니,3시간배송', '', '꽃집,꽃배달', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4037115624', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4037115624', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4037115624', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_4180189865', '춘자플라워전국꽃배달,축하화환,근조화환,개업화분', '', '꽃집,꽃배달', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4180189865', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4180189865', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4180189865', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_252722398', '장미농원', '', '꽃집,꽃배달', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_252722398', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_252722398', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_252722398', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1811482725', '에이프레임스튜디오 개포점', '', '사진,스튜디오', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1811482725', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1811482725', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1811482725', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3969773704', '아르누보스튜디오 일원점', '', '사진,스튜디오', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3969773704', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3969773704', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3969773704', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3204793376', '시그널스튜디오 강남점', '', '사진,스튜디오', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3204793376', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3204793376', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3204793376', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_4157738118', '원스데이 스튜디오', '', '사진,스튜디오', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4157738118', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4157738118', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4157738118', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3387320349', '디어제이 스튜디오', '', '사진,스튜디오', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3387320349', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3387320349', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3387320349', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3996224914', '서울특별시 강남구', '', '생선회', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3996224914', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3996224914', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3996224914', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3427492208', '강원특별자치도 강릉시 강남동', '', '닭갈비', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3427492208', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3427492208', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3427492208', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3651991759', '강원특별자치도 춘천시 강남동', '', '요리주점', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3651991759', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3651991759', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3651991759', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2676370977', '경상북도 안동시 강남동', '', '생선회', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2676370977', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2676370977', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2676370977', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_4041856007', '경상남도 진주시 강남동', '', '한식', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4041856007', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4041856007', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4041856007', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1478016158', '강원특별자치도 강릉시', '', '해물,생선요리', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1478016158', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1478016158', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1478016158', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1363078867', '찜사랑 생선찜전문점', '', '두부요리', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1363078867', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1363078867', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1363078867', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2534014571', '강릉길감자', '', '생선회', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2534014571', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2534014571', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2534014571', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2076975983', '강릉짬뽕순두부 동화가든 본점', '', '생선구이', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2076975983', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2076975983', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2076975983', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3566139320', '강릉 고고횟집', '', '한식', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3566139320', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3566139320', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3566139320', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3647039277', '강남', '', 'cut', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3647039277', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3647039277', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3647039277', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_345181363', '강남구미용실', '', 'perm', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_345181363', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_345181363', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_345181363', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1332511919', '르블라썸 강남점', '', 'perm', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1332511919', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1332511919', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1332511919', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3995976984', '아르결 강남점', '', 'color', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3995976984', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3995976984', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3995976984', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3668783539', '준오헤어 강남역스퀘어점', '', 'perm', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3668783539', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3668783539', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3668783539', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1069299856', '홍대', '', '카페,디저트', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1069299856', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1069299856', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1069299856', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1447107342', '오퍼 카페', '', '카페,디저트', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1447107342', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1447107342', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1447107342', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_321774232', '조블라 홍대점', '', '카페,디저트', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_321774232', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_321774232', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_321774232', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_846383518', '아메리카노', '', '카페,디저트', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_846383518', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_846383518', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_846383518', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_752887664', '에그타르트', '', '카페,디저트', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_752887664', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_752887664', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_752887664', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2622844139', '부산', '', '요리주점', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2622844139', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2622844139', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2622844139', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_4219653822', '민생주', '', '요리주점', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4219653822', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4219653822', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4219653822', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3124672262', '간빠진새', '', '이자카야', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3124672262', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3124672262', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3124672262', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2162297781', '목화실비', '', '요리주점', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2162297781', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2162297781', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2162297781', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1342525719', '초힛사츠', '', '요리주점', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1342525719', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1342525719', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1342525719', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_4164310754', '제주', '', '카페,디저트', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4164310754', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4164310754', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4164310754', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1982440264', '카페 더 콘테나 제주', '', '카페,디저트', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1982440264', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1982440264', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1982440264', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3505647553', '서귀포 제주에인감귤밭 카페', '', '카페,디저트', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3505647553', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3505647553', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3505647553', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1798967162', '리버브제주', '', '카페,디저트', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1798967162', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1798967162', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1798967162', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_4113725120', '라바르', '', '카페,디저트', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4113725120', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4113725120', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4113725120', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_4228455727', '서면역 부산1호선', '', '양식', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4228455727', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4228455727', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4228455727', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2309233042', '판나', '', '닭갈비', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2309233042', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2309233042', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2309233042', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2333972532', '바모스타코 전포점', '', '육류,고기요리', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2333972532', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2333972532', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2333972532', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3038837064', '장인닭갈비 서면점', '', '멕시코,남미음식', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3038837064', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3038837064', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3038837064', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1190002250', '돼지나무 사랑걸렸네 부산 서면 본점', '', '뷔페', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1190002250', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1190002250', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1190002250', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1159798951', '건대', '', '요리주점', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1159798951', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1159798951', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1159798951', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1366445668', '만경상회 건대본점', '', '요리주점', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1366445668', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1366445668', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1366445668', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1900363269', '아리계곡 건대점', '', '요리주점', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1900363269', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1900363269', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1900363269', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_442958209', '서교주담 건대', '', '요리주점', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_442958209', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_442958209', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_442958209', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1044367529', '민지슈퍼 건대본점', '', '요리주점', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1044367529', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1044367529', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1044367529', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2934649475', '연남동', '', '카페,디저트', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2934649475', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2934649475', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2934649475', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2962494549', '연트럴다방 연남', '', '케이크전문', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2962494549', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2962494549', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2962494549', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3528685696', '두바이쫀득쿠키', '', '카페,디저트', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3528685696', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3528685696', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3528685696', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3020505233', '마사비스 카페 연남점', '', '카페,디저트', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3020505233', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3020505233', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3020505233', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2943526726', '피오니 연남점', '', '카페,디저트', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2943526726', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2943526726', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2943526726', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2898664879', '수퍼메이크짐 헬스&PT 수원 인계점', '', '헬스장', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2898664879', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2898664879', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2898664879', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1335383292', '밀라노짐 광교점', '', '스포츠시설', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1335383292', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1335383292', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1335383292', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2240545915', '짐피크 PT 헬스 수원인계점', '', '헬스장', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2240545915', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2240545915', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2240545915', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2237280761', '도미디피트니스 광교점', '', '헬스장', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2237280761', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2237280761', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2237280761', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1366429976', '좋은습관 PT STUDIO 수원인계', '', '스포츠시설', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1366429976', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1366429976', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1366429976', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_4071517477', '메디컬 재활PT&필라테스&헬스', '', '스포츠시설', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4071517477', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4071517477', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_4071517477', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_2925406897', '비무브짐24 헬스&PT 상인점', '', '헬스장', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2925406897', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2925406897', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_2925406897', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1812991916', '하노버 메디칼 운동센터 & 재활PT', '', '스포츠시설', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1812991916', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1812991916', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1812991916', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_3636142400', '옐로우짐 만촌역점 헬스&PT&필라테스&요가&줌바', '', '헬스장', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3636142400', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3636142400', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_3636142400', '가성비좋아요', '', 3);
INSERT IGNORE INTO industry_master (business_id, name, category_code, category_path, algorithm_type) VALUES ('html_1048187627', '더 미 필라테스 범어점', '', '필라테스', 'TYPE_A');
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1048187627', '청결해요', '', 5);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1048187627', '친절해요', '', 7);
INSERT IGNORE INTO keyword_templates (business_id, keyword, keyword_code, cnt) VALUES ('html_1048187627', '가성비좋아요', '', 3);